name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  CARGO_BUILD_JOBS: 2

jobs:
  test:
    name: Build & Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Homebrew
      uses: Homebrew/actions/setup-homebrew@main
      
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: wasm32v1-none
        
    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-stellar-${{ hashFiles('**/Cargo.lock') }}-v1
        
    - name: Install Stellar CLI
      run: brew install stellar-cli
        
    - name: Run unit tests
      run: cargo test -p tic-tac-toe
      
    - name: Run integration tests
      run: cargo test -p tic-tac-toe-integration-tests
      
    - name: Build contract
      run: stellar contract build
        
    - name: Check formatting
      run: cargo fmt --all -- --check
      
    - name: Run clippy
      run: cargo clippy --all-targets --all-features -- -D warnings

    - name: Upload contract artifact
      uses: actions/upload-artifact@v4
      with:
        name: tic-tac-toe-contract
        path: target/wasm32v1-none/release/tic_tac_toe.wasm
        